---
# This playbook installs HAProxy and HTTPd and configures it.
#
- name: Install haproxy
  yum: name={{ item }} state=present
  with_items:
    - haproxy
  when: inventory_hostname in groups['balancers']

- name: Configure the haproxy cnf file
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=644
  notify: restart haproxy
  when: inventory_hostname in groups['balancers']

- name: Start the haproxy service
  service: name=haproxy state=started enabled=yes
  when: inventory_hostname in groups['balancers']

- name: Install firewalld
  yum:
    name: firewalld
    state: present
  when: inventory_hostname in groups['balancers']

- name: Start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  when: inventory_hostname in groups['balancers']

- name: Enable http in firewall
  firewalld: service=http permanent=true state=enabled immediate=true
  when: inventory_hostname in groups['balancers']

