---
- name: webcontent 
  hosts: dev
  remote_user: devops
  become: yes
  tasks:
    - name: Install pkgs
      yum:
        name:
          - httpd
          - firewalld
        state: latest
 
    - name: start service
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - firewalld

    - name: Allow in firewall
      firewalld:
        service: http
        state: enabled
        immediate: yes
        permanent: yes
    
    - name: create a /webdev dir
      file:
        path: /webdev
        state: directory
        mode: 2775
        group: devops
        setype: httpd_sys_content_t

    - name: create a index.html file
      copy:
        content: Development
        dest: /webdev/index.html
        setype: httpd_sys_content_t
      notify: restart httpd

    - name: create a link
      file:
        src: /webdev 
        dest: /var/www/html/webdev
        state: link
        force: yes
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted


