---

- name: Install and Update packages

  hosts: all

  tasks:

    - name: install php and maria
      yum:
        name: "{{ item }}"
        state: latest
      loop: 
        - php
        - mariadb
      when: inventory_hostname in groups['dev'] or inventory_hostname in groups['test'] or inventory_hostname in groups['prod']
    
    - name: inastall develop tools 
      yum:
        name: "@RPM Development tools"
        state: present
      when: inventory_hostname in groups['dev']

    - name: update all
      yum:
        name: '*'
        state: latest
      when: inventory_hostname in groups['dev']
 
